<div class="content-left">
	<div class="row1">
		<div class="img">
			<?php echo $this->Html->image('img1.jpg',array("height"=>"101","width"=>"157"));?>
		</div>
		<div class="welcome">
			<h1 class="title">Welcome to <span>Your Company</span></h1>
			<p><strong>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</strong><br>
				Lorem Ipsum has been the industry's standard dummy text ever since the
				1500s, when an unknown printer took a galley of type and scrambled it
				to make a type specimen book. It has survived not only five centuries,
				but also the leap into electronic typesetting, remaining essentially
				unchanged. sn book. It has survived not only five centuries, but also
				the leap into electronic typesetting, remaining essentially unchanged.
			</p>
	    </div>
	</div>
	<div class="row2">
		<div class="section1">
			<h2 class="subtitle">What&#8217;s New</h2>
			<p><strong>Lorem Ipsum is simply dummy text of the<br> printing and typesetting industry.</strong><br>
				Lorem Ipsum has been the industry's standard<br>
				dummy text ever since the 1500s, when an<br>
				unknown printer took a galley of type and
			</p>
			<p>&nbsp;</p>
			<p>&nbsp;</p>
			<p><a href="#" class="more">read more</a></p>
		</div>
		<div class="section2">
			<h2 class="subtitle">Resources</h2>
			<p><strong>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</strong><br>
				Lorem Ipsum has been the industry's standard dummy text ever since the
				1500s, when an unknown printer took a galley of type and scrambled it
				to make a type specimen book. It has survived not only five centuries, but
			</p>
			<p>&nbsp;</p>
			<p><a href="#" class="more">read more</a></p>
		</div>
	</div>
</div>	