<div class="bottom">
	<ul>
	  <li><a href="<?php echo $this->Html->url(array("controller"=>"Home","action"=>"index"));?>">Home</a></li>
	  <li><a href="<?php echo $this->Html->url(array("controller"=>"Home","action"=>"booking"));?>">Book Now</a></li>
	  <li><a href="#">What's&nbsp;New</a></li>
	  <li><a href="http://booking.arrive.net/nexres/search/power_search.cgi?header=hoteldeals&footer=hoteldeals&src=10031625">Search Hotels</a></li>
	  <li><a href="#">Contact</a></li>
	  <li><a href="http://arrive.net/blog">Blog</a></li>
	  <li><a href="#">Links</a></li>
	</ul>
</div>